spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB

web:
  upload-path: /home/chuckie/Pictures/
#  upload-path: D:/images/

server:
  servlet:
    context-path: /api

log4j
